version: "3.4"
services:
  mysql:
    image: "mysql:5.7"
    container_name: mysql
    ports:
     - "3306:3306"
    environment:
     - "MYSQL_ROOT_PASSWORD=secret"
    volumes:
     - mysql:/var/lib/mysql
    networks:
     - mynet
  php:
    image: webserver
    build: .
    ports:
     - "80:80"
    networks:
     - mynet
volumes:
  mysql:
    external: true
networks:
  mynet: