version: "3.4"
services:
  mysql:
    image: mysql:5.7 # keine port konfiguration da die container untereinander über ihr netzwerk kommunizieren
    container_name: mysql
    environment:
     MYSQL_ROOT_PASSWORD: secret
    volumes:
     - mysql:/var/lib/mysql
    networks:
     - mynet
  webserver:
    image: webserver
    build: .
    container_name: webserver
    ports:
     - "80:80"
    volumes:
     - ./app:/var/www/html
    networks:
     - mynet
volumes:
  mysql:
    external: true
networks:
  mynet: