version: "3.4"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
     - "3306:3306"
    environment:
     MYSQL_ROOT_PASSWORD: secret
    volumes:
     - mysql:/var/lib/mysql
volumes:
  mysql:
    external: true