version: "3.6"
services:
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
     - "MYSQL_ROOT_PASSWORD=secret"
    volumes:
     - mysql:/var/lib/mysql
    networks:
     - mynet
  webserver:
    image: webserver
    ports:
     - "80:80"
    networks:
     - mynet
    deploy:
     replicas: 3
volumes:
  mysql:
    external: true
networks:
  mynet:
    external: true