version: "3.4"
services:
  mysql:
    image: mysql:5.7
    environment:
     MYSQL_ROOT_PASSWORD: secret
    volumes:
     - mysql:/var/lib/mysql
    networks:
     - mynet
    ports:
     - "3306:3306"
    deploy:
     placement:
      constraints: [node.role == manager]
  webserver:
    image: maxkaemmerer/webserver
    ports:
     - "80:80"
    networks:
     - mynet
    deploy:
     replicas: 1
     placement:
      constraints: [node.role == worker]
volumes:
  mysql:
    external: true
networks:
  mynet:
    external: true
    driver: overlay
    attachable: true